<?php

namespace Drupal\openig_sql_migrate\Plugin\migrate\source;

use Drupal\migrate\Annotation\MigrateSource;
use Drupal\migrate\Plugin\migrate\source\SqlBase;
use Drupal\migrate\Row;
use Drupal\taxonomy\Entity\Term;

/**
 * Minimalistic example for a SqlBase source plugin.
 *
 * @MigrateSource(
 *   id = "users",
 *   source_module = "openig_sql_migrate",
 * )
 */
class Users extends SqlBase {

  /**
   * {@inheritdoc}
   */
  public function query() {
    $query = $this->select('auth_user', 'u');
    $query->distinct();
    $query->leftJoin('idgo_admin_profile','p', 'p.user_id = u.id');
    $query->leftJoin('idgo_admin_organisation','o', 'o.id = p.organisation_id');

    $query->fields('u', [
        'id',
        'username',
        'email',
        'last_login',
        'is_active',
        'is_staff',
        'first_name',
        'last_name',
        'date_joined',
    ]);
    $query->addField('p', 'phone');
    $query->addField('p', 'is_admin');
    $query->addField('p', 'organisation_id');

    // Exclude neogeo
    $query->condition('u.email', '%@neogeo%', 'NOT LIKE');
    $query->condition('u.username', 'admin', 'NOT LIKE');
   
    
    $users = ['cadastre@agedi.fr',
    'agedi@agedi.fr',
    'gwenael.martin@afigeo.asso.fr',
    'rodolphe.deletage@adine-aveyron.fr',
    'olivier.maratuech@adine-aveyron.fr',
    'helene.corvisier@agencedespyrenees.fr',
    'jerome.desboeufs@beta.gouv.fr',
    'contact@pcrs.beta.gouv.fr',
    'luca.facciano@unibs.it',
    'bailly@agroparistech.fr',
    'celia.bresson@agroparistech.fr',
    'margaud.dieffenbacher@agroparistech.fr',
    'frederic.portet@agroparistech.fr',
    'cyprien.vialis@agroparistech.fr',
    'helene.durand@alise-geomatique.fr',
    'violaine.meslier@arb-occitanie.fr',
    'emilie.dufresne@arec-occitanie.fr',
    'aqua.fontedit@gmail.com',
    'asa-ba.harold@orange.fr',
    'canalthuir@outlook.fr',
    'direction@asagignac.fr',
    'asa.ducanaldelaplaine2@gmail.com',
    'aseaude@gmail.com',
    'contact@bassin-tarn-aveyron.fr',
    'contact@pastoralisme66.fr',
    'isabelle.boulet@aua-toulouse.org',
    'virginie.choppin@aua-toulouse.org',
    'arnaud.mayis@aua-toulouse.org',
    'philip@audat.org',
    'nicolas.caparros@audrna.com',
    'harmonie.dagneau@audrna.com',
    'lise.grolleau@audrna.com',
    'david.retourna@audrna.com',
    'marc.sainte-croix@audrna.com',
    'laure.bigourdan@aurav.org',
    'serge.herviou@aurca.org',
    'nourredine.idir@aurca.org',
    'emmanuel.meunier@aurca.org',
    'fallary@avineon.com',
    'ineghina@avineon.com',
    'contact@betechsud.com',
    'steven.tanguy@belenergia.com',
    'y.balouin@brgm.fr',
    'j.fournely@brgm.fr',
    'b.monod@brgm.fr',
    'e.palvadeau@brgm.fr',
    'camille.jourdan@brl.fr',
    'brice.tinel@brl.fr',
    'kathy.cano@cesml.fr',
    'julien.garcia@cesml.fr',
    'canal.bohere@wanadoo.fr',
    'didier.brazeau@canigo-grandsite.fr',
    'l.cadene@cc-aglyfenouilledes.fr',
    'y.font@cc-aglyfenouilledes.fr',
    'commune-de-lansac@orange.fr',
    'c.march@cc-aglyfenouilledes.fr',
    'hoda.el-haddouni@cc-acvi.com',
    'francois-xavier.halle@cc-acvi.com',
    'xavier.sudre@cc-acvi.com',
    'urbanisme@cc-aspres.fr',
    'maya.rajaut@avant-monts.fr',
    'sig@laterredargence.fr',
    'sig@laterredargence.fr',
    'n.jeanjean@cac-ts.fr',
    'mairie-plantiers@orange.fr',
    'bremy@cdcganges.fr',
    'jf.raulet@ceze-cevennes.fr',
    'informatique@coeurdelozere.fr',
    'lubrano.jerome@conflentcanigo.fr',
    'sig@c3sm.fr',
    'remi.lagoin@grand-figeac.fr',
    'b.nouvet@cc-gevaudan.fr',
    'sophie.gras@grandorb.fr',
    'kelly.stolar@grandorb.fr',
    'j.miossec@ccgpsl.fr',
    'ccha@ccha-langogne.com',
    'sig@haut-vallespir.fr',
    'g.dupuy@ladomitienne.com',
    'l.poblador@ladomitienne.com',
    'mcatala@lodevoisetlarzac.fr',
    'rralite@eau-lodevois.fr',
    'j.tailhan@cc-sud-herault.fr',
    'julien.ramond@ccmlhl.fr',
    'c.correia@ccpaysdesommieres.fr',
    'c.dauce@ccpaysdesommieres.fr',
    'sig@ccpaysduzes.fr',
    's.bouet-roussel@ccpaysduzes.fr',
    'e.foulquier@cc-paysviganais.fr',
    'sandrine.lathuillere@cc-petitecamargue.fr',
    'j.milliot@piemont-cevenol.fr',
    'sig@cc-pontdugard.fr',
    'thomas.guilbert@pyreneesaudoises.fr',
    'guillaume.andrieu@pyrenees-cerdagne.com',
    'josselin.benkemoun@ccphg.fr',
    'p.dulon@ccphg.fr',
    'lblum@ccrvv.fr',
    'urbanisme@roussillon-conflent.fr',
    'f.verloo@roussillon-conflent.fr',
    'd.cornillon@cc-sud-herault.fr',
    'g.laurant@cc-sud-herault.fr',
    'direction@saintchinian.fr',
    'david.payri@sudroussillon.fr',
    'p.paulet@terredecamargue.fr',
    'sandrine.calmels@cc-vallee-herault.fr',
    'jason.crebassa@cc-vallee-herault.fr',
    'service.sig@cc-vallee-herault.fr',
    'admin.sig@haut-vallespir.fr',
    'se.urbanisme@vallespir.com',
    'charles.loiseau@univ-perp.fr',
    'gilles.fouvet@cerema.fr',
    'leslie.saint-geniez@haute-garonne.chambagri.fr',
    'matthieu.augustin@lozere.chambagri.fr',
    'hugo.brancorsini@aude.chambagri.fr',
    'constance.colombier@aude.chambagri.fr',
    'cazade@herault.chambagri.fr',
    'demessaz@herault.chambagri.fr',
    'joulie-bonnet@herault.chambagri.fr',
    'leonor.perezmerle@herault.chambagri.fr',
    'petit@herault.chambagri.fr',
    'lali.sostre@herault.chambagri.fr',
    'a.doussoux@pyrenees-orientales.chambagri.fr',
    'catherine.irr@gard.chambagri.fr',
    's.mathe@gard.cci.fr',
    'gabrielcausera@beziers-mediterranee.fr',
    'gaetanprulhiere@beziers-mediterranee.fr',
    'edouard.jun@ccrlcm.fr',
    'mairie.ansignan@wanadoo.fr',
    'mairie.brignon@wanadoo.fr',
    'mairie.brissac@wanadoo.fr',
    'c.cantos@calvisson.com',
    'mairie.caramany@wanadoo.fr',
    'serge.terentieff@ville-clermont-herault.fr',
    'mairiedefougaron@orange.fr',
    'policemunicipale@latourdefrance.fr',
    'mairie@latourdefrance.fr',
    'mairie.l-estrechure@wanadoo.fr',
    'jeremie.hanke@ville-lunel.fr',
    'urbanisme@mairie-millas.fr',
    'abdoul-maghed@mairie-perpignan.com',
    'delaval.nicolas@mairie-perpignan.com',
    'mairie.prugnanes@wanadoo.fr',
    'dthibaudeau@rivesaltes.fr',
    'camille.claudin@saint-ambroix.com',
    'mairie.saintandredemajencoules@wanadoo.fr',
    'cp@shb30.com',
    'mairie.st-maurice-de-cazevieille@wanadoo.fr',
    'mairie@saint-arnac.fr',
    'stcesairedegauzignan@orange.fr',
    'urbanisme@stcyprien.fr',
    'mairiehippolytedecaton@gmail.com',
    'mairie-st-martin@wanadoo.fr',
    'mairie.saumane@orange.fr',
    'mairie-de-souanyas@orange.fr',
    'contact@mairiedesournia.fr',
    'urbanisme@sumene.fr',
    'christiane.recolin@valdaigoual.fr',
    'christiane.recolin@valdaigoual.fr',
    'bruno.soler@vauvert.com',
    'commune.euzet@wanadoo.fr',
    'fenouillet.mairie.66@wanadoo.fr',
    'informatique@lesoler.com',
    'mairielevivier@gmail.com',
    'a.lucas@crbe.fr',
    'stephane.rolle@crige-paca.org',
    'antoine.delarue@cnpf.fr',
    'ncatala@cypres.org',
    'stephane.le-guerroue@aude.gouv.fr',
    'franck.vandeputte@aude.gouv.fr',
    'veronique.barbet@gard.gouv.fr',
    'jean-luc.crespi@pyrenees-orientales.gouv.fr',
    'bruno.maranges@pyrenees-orientales.gouv.fr',
    'loic.arthur@cd31.fr',
    'bruno.combes@cd31.fr',
    'olivia.froidefon@cd31.fr',
    'karine.lesage@cd31.fr',
    'fabrice.thevenon@cd31.fr',
    'bmarnat@lozere.fr',
    'swatremez@lozere.fr',
    'mbonrepaux@ariege.fr',
    'lguiavarch@ariege.fr',
    'agnes.bataille@aude.fr',
    'joel.brouillet@aude.fr',
    'margot.chabanais@aude.fr',
    'samuel.delorme@aude.fr',
    'clement.depoix@aude.fr',
    'christophe.gonzalez@aude.fr',
    'julie.rondole@aude.fr',
    'fanny.angles@aveyron.fr',
    'caroline.fabre@aveyron.fr',
    'laurent.romiguiere@aveyron.fr',
    'farnal@herault.fr',
    'cchastagnol@herault.fr',
    'orgarcia@herault.fr',
    'cgasc@herault.fr',
    'yjazeron@herault.fr',
    'alafaye@herault.fr',
    'abniang@herault.fr',
    'yrequi@herault.fr',
    'aymeric.conan@ha-py.fr',
    'camille.hulin@ha-py.fr',
    'florence.pouyenne@ha-py.fr',
    'imen.boulabiar@cd66.fr',
    'yvan.martzluff@cd66.fr',
    'valentin.bouvet@gard.fr',
    'sig.gard@gard.fr',
    'lydia.courret@gard.fr',
    'frederic.delhoume@gard.fr',
    'thomas.fontaine@gard.fr',
    'michael.galien@gard.fr',
    'gregory.noual@gard.fr',
    'obarasz@gers.fr',
    'obonnefon@gers.fr',
    'cdujardin@gers.fr',
    'flaby@gers.fr',
    'tline@gers.fr',
    'laurent.firmin@agriculture.gouv.fr',
    'philippe.hans@agriculture.gouv.fr',
    'laurent.ugliera@agriculture.gouv.fr',
    'cyril.montoya@culture.gouv.fr',
    'cts.opm@ufolep.org',
    'pauline.cabirol@developpement-durable.gouv.fr',
    'julien.chailloux@edf-re.fr',
    'antoine.juston@edf-re.fr',
    'akerr@eid-med.org',
    'nnouviaire@eid-med.org',
    'charlottetrosseille@ellipsig.fr',
    'kevin.sannac@enedis.fr',
    'quentin.boulard@enoe-energie.fr',
    'jedossa@ymail.com',
    'observatoire@causses-et-cevennes.fr',
    'laurent.crotet@envilys.com',
    'technique.chassezac@ardeche-eau.fr',
    'inondations@ardeche-eau.fr',
    'technique.affluents@ardeche-eau.fr',
    'antony.meunier@smbfh.fr',
    'p.negre@les-gardons.fr',
    'p.negre@les-gardons.fr',
    'hf.syble@gmail.com',
    'k.adoul@vidourle.org',
    'contact@vistre-vistrenque.fr',
    'joan.devictor@epflr.fr',
    'fdaiherault@gmail.com',
    'fedec66@wanadoo.fr',
    'adeline.herault@peche66.org',
    'aubrac@fplg.fr',
    'foretprivee09@gmail.com',
    'thierry.gras.vidal@gmail.com',
    'e.algans@fredonoccitanie.com',
    'sylvain.fort@gaillac-graulhet.fr',
    'k.storm@geofit.fr',
    'ecandaele@icv.fr',
    'jerome.gourmelon@grandavignon.fr',
    'thierry.monbrun@hautegaronnenumerique.fr',
    'carole.jarrassier@atd31.fr',
    'd.bouyer@herault-energies.fr',
    'd.laurent@agglohm.net',
    'banton@hydriad.com',
    'karl.azemar@gmail.com',
    'jefbehm@gmail.com',
    'thomas.michel@idgeo.fr',
    'y.denis@i-emn.fr',
    'alice.argentero@inrae.fr',
    'zoe.chastin@inrae.fr',
    'lea.courteille@inrae.fr',
    'nina.graveline@inrae.fr',
    'philippe.lagacherie@inrae.fr',
    'marie-noel.mistou@inrae.fr',
    'fabrice.vinatier@inrae.fr',
    'philippe.abadie@ign.fr',
    'sebastien.bourdeau@ign.fr',
    'lionel.gaudiot@ign.fr',
    'frederic.landais@ign.fr',
    'laurent.muscarnera@ign.fr',
    'sandy.muscarnera@ign.fr',
    'j.racaniere@inao.gouv.fr',
    'sig@syndicat-cotesdurhone.com',
    'vincent.delbar@latelescop.fr',
    'bastien.nguyen@latelescop.fr',
    'marion.houles@lavionjaune.fr',
    'c.seard@legrandnarbonne.com',
    'e.sole@legrandnarbonne.com',
    'r.sorlin@legrandnarbonne.com',
    'sig@euziere.org',      
    'eric.fournier@lot.fr', 
    'jean-yves.garinet@magellium.fr',
    'commune-de-lesquerde@orange.fr',
    'biodiversite@vailhauques.fr',
    'anthony.pujol@metapolis.fr',
    'frederic.fayolle@ville-montpellier.fr',
    'patrick.jochum@montpellier.fr',
    'amelie.labbe@ville-montpellier.fr',
    'r.lachhab@montpellier3m.fr',
    'alix.marc@montpellier3m.fr',
    'as.muepu@montpellier3m.fr',
    'valerie.ronzetti@montpellier.fr',
    'c.valot@saintjeandevedas.fr',
    'ltur@groupe-sirius.fr',
    'j.kamdoumngueuko@naturalia-environnement.fr',
    'daoudambodjj@gmail.com',
    'pascal.guieysse@nimes.fr',
    'sig@nimes-metropole.fr',
    'nicolas.lambert@nimes.fr',
    'frederic.moll@nimes.fr',
    'marie-gil.septfonds@nimes.fr',
    'nicolas.landes@onf.fr',
    'bernardmcj@hotmail.com',
    'carauxgarson@gmail.com',
    'fdeblomac@decryptageo.fr',
    'geosoleau@sfr.fr',
    'lemoux.patrice@gmail.com',
    'president@openig.org',
    'bsegala@vu2o.fr',
    'eddie.balaye@cevennes-parcnational.fr',
    'jerome.bussiere@parc-grands-causses.fr',
    'jean-francois.raymond@parc-grands-causses.fr',
    'mario.bon@coeur-herault.fr',
    'noel.carreno@coeur-herault.fr',
    'lara.mornet-hess@coeur-herault.fr',
    'sig@payspyreneesmediterranee.org',
    'animation@ptcm.fr',
    'cdepoix@ptcm.fr',
    'pefc.occitanie@gmail.com',
    'f.carvalhais@perpignan-mediterranee.org',
    'a.catinaud@canetenroussillon.fr',
    'f.porte@perpignan-mediterranee.org',
    'd.rouffart@perpignan-mediterranee.org',
    'f.urville@perpignan-mediterranee.org',
    'ybancillon@petr-gevaudan-lozere.fr',
    'a.fesquet@corbieres-fenouilledes.fr',
    'j.mazardo@corbieres-fenouilledes.fr',
    'f.richart@pnrnm.fr',
    'anthony.yard@parc-pyrenees-catalanes.fr',
    'laetitia.bejanin@parc-pyrenees-catalanes.fr',
    'silvana.gargiulo@parc-pyrenees-catalanes.fr',
    'esther.lasar@parc-pyrenees-catalanes.fr',
    'philippe.mignon@parc-pyrenees-catalanes.fr',
    'virgile.baudrot@qonfluens.com',
    'johanna.bonnefoy@laregion.fr',
    'camille.debrock@laregion.fr',
    'carole.desmarais@laregion.fr',
    'delphine.drajkowski@laregion.fr',
    'claire.faroux@laregion.fr',
    'hugo.le-charpentier@laregion.fr',
    'pierre.pageau@laregion.fr',
    'herve.soulie@laregion.fr',
    'marie.terrier@laregion.fr',
    'david.vazelle@laregion.fr',
    'loeiz.briantais@espaces-naturels.fr',
    'christophe.hurson@espaces-naturels.fr',
    'jean-alexis.noel@mairie-leucate.fr',
    'g.prabel@rp-global.com',
    'rachel.magana@territoire30.com',
    'maud.chevignon@safer-occitanie.fr',
    'gilles.lefrancois@safer-occitanie.fr',
    'maelle.decherf@sce.fr',
    'vincentreynes@scot-biterrois.fr',
    's.guitart@sde09.fr',
    'f.falcon@sdee48.fr',
    'r.couret@sdis30.fr',
    'n.vaginay@sdis30.fr',
    'benoit.monteverde@intranet-sdis11.fr',
    'rafaelle.gutton@sdis34.fr',
    'nicolas.moyroud@sdis34.fr',
    'hbessiere@sdis48.fr',
    'arnaud.dufaure@sdis65.fr',
    'eric.samalens@sdis65.fr',
    'kevin.berva@sdis66.fr',
    'yannick.roussel@sdis66.fr',
    'sig@agglopole.fr',
    'v.roux@agglopole.fr',
    'dconstant@siig.fr',
    'l.cesmat@smbt.fr',
    'jp.roussillon@smbt.fr',
    'riviere.agly@gmail.com',
    'bv.agly@gmail.com',
    'contact@reart66.fr',
    'brochier@camarguegardoise.com',
    'p.gasulla@smdea09.fr',
    'gmombertrand@smeta.fr',
    'sig-dst@smevh.fr',
    't.clemencet@gorgesdugardon.fr',
    'c.helissey@gorgesdugardon.fr',
    'd.munck@gorgesdugardon.fr',
    'f.chay@smica.fr',
    't.mayrand@smica.fr',
    'j.serieye@smica.fr',
    'c.soulie@smica.fr',
    'sage@syndicatdutech.fr',
    'thomas.portier@smmar.fr',
    'antony.bartolo@reseau.sncf.fr',
    'ext.eric.spinosa@reseau.sncf.fr',
    'driss.zeroili@reseau.sncf.fr',
    'msw@sogefi-sig.com',
    'juliette.domage@sogefi-sig.com',
    'secretariat@spanc66.fr',
    'nicolas.clarin@strada-ingenierie.fr',
    'nicolas.delpoux@syaden.fr',
    'philippe.medina@syaden.fr',
    'pascal.mosti@syaden.fr',
    'lionelvidal@sydeel66.com',
    'antoine.castagnet@symadrem.fr',
    'e.roujon@symadrem.fr',
    'saint-chinian.tech@wanadoo.fr',
    'contact@syndicatbaslanguedoc.com',
    'ugolin.bourbon-denis@parc-naturel-aubrac.fr',
    'cloe.garrel@parc-naturel-aubrac.fr',
    'marie.hastaran@parc-naturel-aubrac.fr',
    'nicolas.leblois@parc-naturel-aubrac.fr',
    'joris.pesche@parc-naturel-aubrac.fr',
    'smgas.sig@orange.fr',
    'ava.hervieu@bassintet.fr',
    'magali.marimon@bassintet.fr',
    'smbv-tarn-amont@orange.fr',
    'ccqb_amenagement@orange.fr',
    'smixtetpcf@orange.fr',
    'g.canar@smld.fr',
    'g.nadal@nappes-roussillon.fr',
    'sylvain.pages@te46.fr',
    'clement.murgue@terranis.fr',
    'michel.daragon@terroiko.fr',
    'alice.martin@tigeo.fr',
    'lionel.viguier@tigeo.fr',
    'cyrielle.mathias@gmail.com',
    'ucic66@gmail.com',
    'sig@asagignac.fr',
    'contact@aigo34.fr',
    'samuel.pont@communesforestieres.org',
    'aurelien.ayme@alumni.univ-avignon.fr',
    'lucie.juncker.etu@univ-lille.fr',
    'hoenigc@students.uni-marburg.de',
    'laure.paradis@umontpellier.fr',
    'nastasmeets@orange.fr',
    'adrien.cheneaux@urbanprojects.fr',
    'yannick.christol-veillet@valorem-energie.com',
    'ines.candela@valorhiz.com',
    'maxime.dumont@valorhiz.com',
    'quentin.hamzaoui@valorhiz.com',
    'florent.rigal@valorhiz.com',
    'olivier.taugourdeau@valorhiz.com',
    'leo.vanel@valorhiz.com',
    'mathis.almas@hotmail.com',
    'direction.albias@info82.com',
    'arsic.biliana@gmail.com',
    'caroline.badouel@univ-toulouse.fr',
    'sandra.barantal@univ-montp3.fr',
    'mairie.saintprive@gmail.com',
    'marilynebarisic@gmail.com',
    'l.bertrand@epode.eu',
    'jean-paul.bessiere@cerema.fr',
    'katherine.broomberg@tercia.fr',
    'christine.buigues@gaxieu.fr',
    'jl.cascales30@gmail.com',
    'collin@agriterra-group.com',
    'jonathan.coutaz@setec.com',
    'declochez.mbetudes@rtigroupe.fr',
    'jean-francois.dejoux@univ-tlse3.fr',
    'sebastien.despaux@trigone-gers.fr',
    'contact@valentindouarre.fr',
    'thomasdouet1@hotmail.fr',
    's.doumbia@wpd.fr',
    'vincent.dufournaud@sege.fr',
    'sofia.ezzyn20@gmail.com',
    'yvonne.ferricelli@gmail.com',
    'theofino14@live.fr',
    'agnes.gil@enedis.fr',
    'marin.guitard@aveyron.chambagri.fr',
    'hermenge.romain@laposte.net',
    'novadapt@ik.me',
    'frederic-labouyrie@wanadoo.fr',
    'hugo.lavrut@gmail.com',
    'r.lecalvez@compagniedupaysage.fr',
    'guilhem.lemasle@gaxieu.fr',
    'bureau.mh2o@gmail.com',
    'clementlombal@hotmail.fr',
    'marie.meletopoulos@urbanis.fr',
    'simon.mellerin@makina-corpus.com',
    'ac.moalic@terraterre.fr',
    'benoit.mutius@proton.me',
    'julienne.piana@inrap.fr',
    'denis.rey@cdc-biodiversite.fr',
    'romain.rignani@neoen.com',
    'gilrodrigues@constructelenergie.fr',
    'sig@artifex-conseil.fr',
    'maximescrinzi@yahoo.fr',
    'sebaaly.georgees@gmail.com',
    'jct@jctheisen.fr',
    'bastien.vaucan@hotmail.fr',
    'nicolas.vila@thalesgroup.com',
    'ph.vincon@wanadoo.fr'];
    
    // Exclude users
    $query->condition('u.email', $users , 'IN');
    // $query->range(0, 1); // limit to 1, debug only
    
    // Do something with each $record

    return $query;
  }

  /**
   * {@inheritdoc}
   */
  public function fields() {
/*
    return [
        'id',
        'legal_name',
        'slug',
        'email',
        'website',
        'description',
        'address',
        'postcode',
        'city',
        'phone',
        'organisation_type_id',
        'organisation_type_name',
        'siren',
        'is_active',
        'is_crige_partner'
    ];
*/
  }

  /**
   * {@inheritdoc}
   */
  public function getIds() {
    return [
      'id' => [
        'type' => 'integer',
        'alias' => 'u',
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function prepareRow(Row $row) {

    // Link de l'organisation vers les structures déjà importés
    $database = \Drupal::database();
    $query = $database->query("SELECT sourceid1, destid1 FROM {migrate_map_structures} WHERE sourceid1 = '".intval($row->getSourceProperty('organisation_id'))."'");
    $results = $query->fetchAllKeyed();

    foreach ($results as $key => $value) {
      if ($key == $row->getSourceProperty('organisation_id')) {
        $row->setSourceProperty('organisation_id', $value);
      }
    }

    // Correction des dates
    $last_login = \DateTime::createFromFormat('Y-m-d H:i:s.uT', $row->getSourceProperty('last_login'));
    if($last_login) $row->setSourceProperty('last_login', $last_login->format('U'));
    
    $date_joined = \DateTime::createFromFormat('Y-m-d H:i:s.uT', $row->getSourceProperty('date_joined'));
    if($date_joined) $row->setSourceProperty('date_joined', $date_joined->format('U'));


    return parent::prepareRow($row);
  }
}

