name: Config OPenIG
type: module
description: Configuration OPenIG
package: Custom
core_version_requirement: ^9 || ^10
dependencies:
  - paragraphs
  - admin_toolbar
  - webform
  - weight
  - sync_uuids
  - openig_adhesion
