# Schema file for the configuration files of the openig_search module.
openig_search.settings:
  type: config_object
  label: 'OpenIG Search Settings'
  mapping:
    external_search_enabled:
      type: boolean
      label: 'Enable external search'
