_core:
  default_config_hash: fMTQlRT4MXb9WtflmxsvPI0VnKTQNjOnlx9oCWO3vYo
langcode: fr
buttons_size: 32
additional_html: "<a class=\"a2a_button_linkedin\">\r\n    <i class=\"fa-brands fa-linkedin-in\"></i>\r\n</a>\r\n<a class=\"a2a_button_x\">\r\n    <i class=\"fa-brands fa-x-twitter\"></i>\r\n</a>\r\n<a class=\"a2a_button_email\">\r\n    <i class=\"fa-solid fa-envelope\"></i>\r\n</a>\r\n<a class=\"a2a_button_facebook\">\r\n    <i class=\"fa-brands fa-facebook-f\"></i>\r\n</a>"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
entities:
  media: 1
  node: 1
  comment: 1
  block_content: 0
  contact_message: 0
  file: 0
  menu_link_content: 0
  path_alias: 0
  search_api_task: 0
  shortcut: 0
  simplenews_subscriber: 0
  simplenews_subscriber_history: 0
  taxonomy_term: 0
  user: 0
  webform_submission: 0
  paragraph: 0
