_core:
  default_config_hash: i_z2pdVLbxvs6u1XQDttLYf7QP0u8sxd1DjV_Jwt1-Y
langcode: fr
back_to_top_prevent_on_mobile: false
back_to_top_prevent_in_admin: true
back_to_top_prevent_in_front: false
back_to_top_button_trigger: 100.0
back_to_top_speed: 1200.0
back_to_top_button_place: 1
back_to_top_button_text: ''
back_to_top_button_type: text
back_to_top_bg_color: '#F0F0EF'
back_to_top_border_color: ''
back_to_top_hover_color: ''
back_to_top_text_color: '#BE1621'
