_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fr
module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  back_to_top: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  ckeditor_font: 0
  color_field: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  custom_breadcrumbs: 0
  custom_view_filters: 0
  daterange_compact: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  hcaptcha: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_per_role: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  nodeaccess: 0
  openig_adhesion: 0
  openig_config: 0
  openig_filter_annuaire: 0
  openig_sql_migrate: 0
  openig_webform: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pgsql: 0
  responsive_image: 0
  search: 0
  search_api: 0
  search_api_solr: 0
  shortcut: 0
  simple_sitemap: 0
  simplenews: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  social_media_links: 0
  social_media_links_field: 0
  structure_sync: 0
  svg_image: 0
  sync_uuids: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_blocks: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_peertube: 0
  views_fieldsets: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  weight: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
  eu_cookie_compliance: 1001
theme:
  olivero: 0
  claro: 0
  stable9: 0
  bootstrap5: 0
  openig: 0
profile: standard
