_core:
  default_config_hash: zmkyvoZ03LGqfVeB0mtslC-pkWMOrGIU9lJl9_jqUkc
langcode: fr
uuid: dbae7d7f-f09a-4507-a8d4-ce636ff128f9
popup_enabled: true
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
eu_countries: {  }
eu_only: false
eu_only_js: false
popup_position: false
fixed_top_position: true
popup_info:
  value: '<h2>Ce site utilise des cookies</h2><p>En cliquant sur accepter, vous consentez à ce fonctionnement.</p>'
  format: full_html
mobile_popup_info:
  value: ''
  format: basic_html
popup_info_template: new
popup_agree_button_message: Accepter
popup_more_info_button_message: 'En savoir plus'
mobile_breakpoint: 768
popup_agreed_enabled: false
popup_hide_agreed: false
disagree_button_label: Refuser
popup_agreed:
  value: '<h2>Thank you for accepting cookies</h2><p>You can now hide this message or find out more about cookies.</p>'
  format: full_html
popup_find_more_button_message: 'More info'
popup_hide_button_message: Masquer
popup_link: /mentions-legales
popup_link_new_window: true
popup_height: null
popup_width: 100%
popup_delay: 1000
show_more_info: true
popup_bg_hex: F0F0EF
popup_text_hex: 0A0909
domain: ''
domains_option: 1
domains_list: ''
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
exclude_admin_theme: true
cookie_session: 0
set_cookie_session_zero_on_disagree: 0
cookie_lifetime: 100
use_mobile_message: false
use_bare_css: false
use_olivero_css: true
disagree_do_not_show_popup: false
reload_page: false
reload_options: 0
reload_routes_list: ''
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
method: opt_in
disabled_javascripts: ''
automatic_cookies_removal: true
allowed_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<h2>Ce site utilise des cookies</h2><div class="module--translations-translatedtext js-module--translations-translatedtext is-placeholder" style="height:216px;">Vous avez donné votre consentement.</div>'
  format: full_html
withdraw_tab_button_label: Cookies
withdraw_action_button_label: 'Retirer son consentement'
withdraw_enabled: true
withdraw_button_on_info_popup: false
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
enable_save_preferences_button: true
domain_all_sites: false
settings_tab_enabled: true
containing_element: body
cookie_policy_version: 1.0.0
cookie_value_disagreed: '0'
cookie_value_agreed_show_thank_you: '1'
cookie_value_agreed: '2'
accessibility_focus: false
close_button_action: close_banner
reject_button_label: ''
reject_button_enabled: false
close_button_enabled: false
dependencies:
  config:
    - filter.format.basic_html
    - filter.format.full_html
