_core:
  default_config_hash: CqlpQWBwxWgF4d1BcwQ_qKL-2mo2exqFqRHeAzyrSwo
site_key: 71863f30-ad50-4eae-819c-29d470e83246
secret_key: 71863f30-ad50-4eae-819c-29d470e83246
hcaptcha_src: 'https://hcaptcha.com/1/api.js'
widget:
  theme: ''
  size: ''
  tabindex: 0
