_core:
  default_config_hash: 2s21v-hdOHG4IFEmUf-z199UgcEdaXGN5qm9K3FIqCY
drupalAcctProvisionServer: ldap
ldapEntryProvisionServer: null
drupalAcctProvisionTriggers:
  - drupal_on_login
  - drupal_on_update_create
ldapEntryProvisionTriggers: {  }
orphanedIncludeDisabledUsers: true
orphanedDrupalAcctBehavior: user_cancel_block
orphanedDrupalAcctReportingInbox: ''
orphanedCheckQty: 100
orphanedAccountCheckInterval: weekly
userConflictResolve: resolve
manualAccountConflict: conflict_associate
acctCreation: ldap_behavior
disableAdminPasswordField: true
userUpdateCronQuery: all_users
userUpdateCronInterval: always
userUpdateOnly: false
ldapUserSyncMappings: {  }
