status: true
langcode: fr
dependencies: {  }
id: users
class: null
field_plugin_method: null
cck_plugin_method: null
migration_tags: null
migration_group: null
label: "Utilisateurs"
source:
  plugin: users
  key: migrate
process:
  name: username
  mail: email
  created: date_joined
  access: last_login
  login: last_login
  status: is_active
  field_firstname: first_name
  field_lastname: last_name
  field_phone: phone
  field_structure/target_id: organisation_id
destination:
  plugin: 'entity:user'
migration_dependencies:
  required:
    - structures
