_core:
  default_config_hash: ev_QLQNwc0-1EGokxDRzrPpUi1kLXjeBRd5vhwpB6h0
langcode: fr
allowed_grant_operations:
  grant_view: true
  grant_update: false
  grant_delete: false
bundles_roles_grants:
  article:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  evenement:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  groupe_de_travail:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  page:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  ressource:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  service:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  simplenews_issue:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  structure:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 1
      grant_delete: 1
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
  temoignage:
    anonymous:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    authenticated:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    content_editor:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    administrator:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    adherent:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
    author:
      grant_view: 1
      grant_update: 0
      grant_delete: 0
grants_tab_availability:
  article: false
  evenement: false
  groupe_de_travail: false
  page: false
  ressource: true
  service: false
  simplenews_issue: false
  structure: false
  temoignage: false
map_rid_gid:
  anonymous: 0
  authenticated: 1
  content_editor: 2
  administrator: 3
  adherent: 4
roles_settings:
  anonymous:
    display_name: 'Utilisateur anonyme'
    name: 'Utilisateur anonyme'
    weight: 0
    selected: true
  authenticated:
    display_name: 'Utilisateur authentifié'
    name: 'Utilisateur authentifié'
    weight: 0
    selected: true
  content_editor:
    display_name: 'Éditeur de contenu'
    name: 'Éditeur de contenu'
    weight: 0
    selected: true
  administrator:
    display_name: Administrateur
    name: Administrateur
    weight: 0
    selected: false
  adherent:
    display_name: Adhérent
    name: Adhérent
    weight: 0
    selected: true
