_core:
  default_config_hash: NFnOZU6VCOfURCAR4-O3V7eMHTx2LNqnCmDKRSNjjns
always_save_userinfo: true
connect_existing_users: true
override_registration_settings: false
end_session_enabled: true
user_login_display: replace
redirect_login: user
redirect_logout: ''
userinfo_mappings:
  timezone: zoneinfo
  field_firstname: middle_name
  field_lastname: family_name
  field_phone: phone_number
role_mappings: {  }
