_core:
  default_config_hash: 7ITcwwShhS7SG3SJdIqRQkzXEcEPNejdEnbeDVDeDY0
script:
  domain: ''
  api: ''
  src: 'https://plausible.openig.org/js/script.file-downloads.js'
dashboard:
  shared_link: ''
visibility:
  enable: true
  admin_route_mode: 0
  request_path_mode: 0
  request_path_pages: ''
  user_role_roles:
    anonymous: '0'
    authenticated: '0'
    content_editor: '0'
    administrator: '0'
    adherent: '0'
  user_role_mode: 0
events:
  403: false
  404: false
