_core:
  default_config_hash: MQ_4kFOzBybKzwsUyT-FJLe20MzZj0tGSPLqXTWQJcg
langcode: fr
hash_expiration: 86400
newsletter:
  issue_tokens: true
  format: html
  priority: 0
  receipt: true
  from_address: webmaster@openig.org
  from_name: 'Occitanie Pyrénées en Intelligence Géomatique'
subscriber:
  sync_fields: true
subscription:
  skip_verification: false
  tidy_unconfirmed: 7
  confirm_subject: 'Confirmation de [site:name]'
  confirm_body: "We have received a request to subscribe [simplenews-subscriber:mail] at [site:url]. To confirm please use the link below.\r\n\r\n[simplenews-subscriber:confirm-url]"
  confirm_subscribe_page: ''
  confirm_unsubscribe_page: ''
  validate_subject: 'Manage your subscriptions at [site:name]'
  validate_body: "We have received a request to manage your subscriptions for [simplenews-subscriber:mail] at [site:url]. To proceed please use the link below.\r\n\r\n[simplenews-subscriber:manage-url]"
mail:
  use_cron: false
  textalt: false
  throttle: 20
  spool_progress_expiration: 3600
  spool_expire: 0
  debug: false
  source_cache: null
