_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
langcode: fr
page_title: Sitemap
message:
  value: ''
  format: plain_text
plugins:
  frontpage:
    enabled: true
    weight: -39
    settings:
      title: ''
      rss: ''
    id: frontpage
    provider: sitemap
  'menu:main':
    enabled: true
    weight: -38
    settings:
      title: 'Navigation principale'
      show_disabled: false
    id: 'menu:main'
    provider: sitemap
  'menu:faq':
    enabled: true
    weight: -37
    settings:
      title: FAQ
      show_disabled: false
    id: 'menu:faq'
    provider: sitemap
  'menu:footer':
    enabled: true
    weight: -36
    settings:
      title: 'Pied de page'
      show_disabled: false
    id: 'menu:footer'
    provider: sitemap
include_css: true
