blocks:
  -
    info: 'Image en bas de page'
    langcode: fr
    uuid: 555f7a44-f502-42f6-be3c-da8191356402
    bundle: image
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '19'
          alt: mesh
          title: ''
          width: '64'
          height: '64'
  -
    info: 'Image en haut de page'
    langcode: fr
    uuid: cc9d0053-0d6f-4f30-aa51-bacb9710c2a3
    bundle: image
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '16'
          alt: mesh
          title: ''
          width: '64'
          height: '64'
  -
    info: 'Dernière newsletter'
    langcode: fr
    uuid: 67095522-a276-4bcb-ac5e-024b0f8e5199
    bundle: lien
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
      field_lien:
        -
          uri: 'internal:/'
          title: 'Voir la dernière newsletter'
          options: {  }
  -
    info: OpenStreetMap
    langcode: fr
    uuid: 51336add-2e63-44f0-b9f3-e0bfabd7b279
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p><iframe src="https://www.openstreetmap.org/export/embed.html?bbox=3.874493837356568%2C43.64427623081348%2C3.8778921961784367%2C43.646040528752174&amp;layer=mapnik" width="415" height="250"></iframe></p>'
          summary: ''
          format: full_html
  -
    info: 'Adresse et contact'
    langcode: fr
    uuid: 062b31d8-76b5-4710-91ac-088969c978c7
    bundle: adresse_et_contact
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>Maison de la télédétection<br>500, rue Jean-François Breton<br>34093 Montpellier Cedex 5</p>'
          summary: ''
          format: basic_html
      field_email:
        -
          value: contact@openig.org
      field_telephone:
        -
          value: '04 67 55 86 54'
menus:
  -
    menu_name: main
    title: OPenIG
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: ac5b7b14-b943-464e-bc9f-77e35bd4eeb6
    options: {  }
  -
    menu_name: main
    title: "Présentation d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 7b5b96bb-1be4-46e9-8642-5d5ecd4251ba
    options: {  }
  -
    menu_name: main
    title: 'Réseaux et partenaires'
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 2937f7ac-a4eb-4bbd-be30-3f0c4e9278e4
    options: {  }
  -
    menu_name: main
    title: "L'association"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: c7e5dd55-4a0b-4326-9ec9-46c9ea34e6ea
    options: {  }
  -
    menu_name: main
    title: "Les adhérents d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: c3dbe0c5-d2f2-4d3d-8967-48f060279769
    options: {  }
  -
    menu_name: main
    title: "L'équipe"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: 9fbd32ea-a578-4b17-abbc-3366c58a23dc
    options: {  }
  -
    menu_name: main
    title: Annuaire
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: ca8bd41d-849b-4006-9ff3-762eeeb17b4b
    options: {  }
  -
    menu_name: main
    title: Données
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: d9144fe6-69e0-4976-819f-6ec224236685
    options: {  }
  -
    menu_name: main
    title: 'Groupe de travail'
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: c1734394-cd4d-42e1-9549-612c89292052
    options: {  }
  -
    menu_name: main
    title: Services
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: fr
    uuid: 59f25bfd-6ad9-4428-80dd-cb76f3c8c7ed
    options: {  }
  -
    menu_name: main
    title: Agenda
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: fr
    uuid: d0168de7-927d-4c5e-8516-19f3a8fd5e2e
    options: {  }
  -
    menu_name: main
    title: Actualités
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: fr
    uuid: 02a94da8-d7ba-4de2-a0bc-1a486ad102be
    options: {  }
  -
    menu_name: footer
    title: 'Mentions légales'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 5b0408e5-146f-4c06-b848-46915d1a93f5
    options: {  }
  -
    menu_name: footer
    title: 'Plan du site'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 7efb7964-3bbd-40c3-96f3-2b2f80869de3
    options: {  }
  -
    menu_name: footer
    title: RGPD
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: bcd022eb-9a4e-4955-bb71-8ab50ed19eaa
    options: {  }
  -
    menu_name: footer
    title: CGU
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: f9b22e23-9d6e-4b17-ac79-1ee475ad9504
    options: {  }
  -
    menu_name: footer
    title: Contact
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: cc1f90e4-b5ef-4cd0-9482-4e876ccbb523
    options: {  }
  -
    menu_name: faq
    title: FAQ
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: fr
    uuid: 676720fd-9c04-441d-9ab1-f4efdf169952
    options: {  }
  -
    menu_name: adhesion
    title: 'Pourquoi adhérer'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: b20fa811-542b-4567-8296-e0cc9ffc0874
    options: {  }
  -
    menu_name: adhesion
    title: 'Mon compte'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: db9dd5ac-fdad-4d99-9771-f62f88e71967
    options: {  }
  -
    menu_name: adhesion
    title: 'Nom utilisateur'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: 1d617429-90b2-45d9-ad43-8e2ab04b0d94
    options: {  }
  -
    menu_name: actions-dans-l-association
    title: Découvrir
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 9eb9e21a-8b97-461b-935c-997b18cefb7f
    options: {  }
  -
    menu_name: actions-dans-l-association
    title: "S'informer"
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 1712e62b-7770-4775-bbe7-29208dee3f2b
    options: {  }
  -
    menu_name: actions-dans-l-association
    title: Participer
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: 62995987-cdd2-4e37-adae-27ab24e462e9
    options: {  }
  -
    menu_name: actions-dans-l-association
    title: Utiliser
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: 25719893-768e-4491-aa9c-295371f0c12a
    options: {  }
