menus:
  -
    menu_name: main
    title: OPenIG
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: ac5b7b14-b943-464e-bc9f-77e35bd4eeb6
    options: {  }
  -
    menu_name: main
    title: "Présentation d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 7b5b96bb-1be4-46e9-8642-5d5ecd4251ba
    options: {  }
  -
    menu_name: main
    title: 'Réseaux et partenaires'
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 2937f7ac-a4eb-4bbd-be30-3f0c4e9278e4
    options: {  }
  -
    menu_name: main
    title: "L'association"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: c7e5dd55-4a0b-4326-9ec9-46c9ea34e6ea
    options: {  }
  -
    menu_name: main
    title: "Les adhérents d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: c3dbe0c5-d2f2-4d3d-8967-48f060279769
    options: {  }
  -
    menu_name: main
    title: "L'équipe"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: 9fbd32ea-a578-4b17-abbc-3366c58a23dc
    options: {  }
  -
    menu_name: main
    title: Annuaire
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: ca8bd41d-849b-4006-9ff3-762eeeb17b4b
    options: {  }
  -
    menu_name: main
    title: Données
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: d9144fe6-69e0-4976-819f-6ec224236685
    options: {  }
  -
    menu_name: main
    title: 'Groupe de travail'
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: c1734394-cd4d-42e1-9549-612c89292052
    options: {  }
  -
    menu_name: main
    title: Services
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: fr
    uuid: 59f25bfd-6ad9-4428-80dd-cb76f3c8c7ed
    options: {  }
  -
    menu_name: main
    title: Agenda
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: fr
    uuid: d0168de7-927d-4c5e-8516-19f3a8fd5e2e
    options: {  }
  -
    menu_name: main
    title: Actualités
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: fr
    uuid: 02a94da8-d7ba-4de2-a0bc-1a486ad102be
    options: {  }
