blocks:
  -
    info: 'Image accueil'
    langcode: fr
    uuid: a6cc63d2-2318-4bb8-a541-90b04b51f360
    bundle: image
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '33'
          alt: mesh
          title: ''
          width: '64'
          height: '64'
  -
    info: 'Message bloc Utiliser inaccessible'
    langcode: fr
    uuid: 80673789-61a5-4014-a53e-6a10209477d9
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>Vous devez être adhérent pour accéder à ce service</p>'
          summary: ''
          format: basic_html
  -
    info: 'La newsletter'
    langcode: fr
    uuid: 71468847-678d-426c-83da-d1243eb1a749
    bundle: bloc_newsletter
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>eu. quis ante nisi Nullam ipsum Lorem vitae vestibulum sollicitudin vestibulum ut vel vestibulum dignissim laoreet scelerisque. non elit. eu. tortor vel at bibendum nisi nisi tortor a tristique. ut vel Donec adipiscing mauris fringilla. nisi sit tristique. Morbi eu. fermentum non at lacinia Maecenas ligula Sed consectetur fringilla.</p>'
          summary: ''
          format: basic_html
      field_image:
        -
          target_id: '104'
          alt: 'Groupe de personnes'
          title: ''
          width: '2034'
          height: '1016'
      field_lien:
        -
          uri: 'internal:/'
          title: 'Voir la dernière newsletter'
          options: {  }
      field_picto:
        -
          target_id: '103'
          alt: Journal
          title: ''
          width: '115'
          height: '103'
  -
    info: "Phrase d'accroche header"
    langcode: fr
    uuid: e14ec2d8-cb66-494e-8514-885a3ede0489
    bundle: texte_et_couleur
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>OPenIG<br>au service de vos territoires en Occitanie</p>'
          summary: ''
          format: basic_html
      field_couleur:
        -
          color: '#F2F6E7'
          opacity: null
      field_lien: {  }
  -
    info: "Phrase d'accroche footer"
    langcode: fr
    uuid: a5776ac5-a497-4338-ad15-3db8d5f724ba
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>Occitanie Pyrénées en Intelligence Géomatique</p>'
          summary: ''
          format: basic_html
  -
    info: 'Vue service'
    langcode: fr
    uuid: 82388b6f-60e8-4c04-acd8-414f10a49a61
    bundle: picto_et_texte
    revision_id: null
    rev_id_current: null
    fields:
      field_picto_et_texte:
        -
          target_id: '190'
          target_revision_id: '419'
        -
          target_id: '191'
          target_revision_id: '420'
        -
          target_id: '192'
          target_revision_id: '421'
        -
          target_id: '193'
          target_revision_id: '422'
  -
    info: 'Image en bas de page'
    langcode: fr
    uuid: 555f7a44-f502-42f6-be3c-da8191356402
    bundle: image
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '19'
          alt: mesh
          title: ''
          width: '64'
          height: '64'
  -
    info: 'Vue groupe de travail'
    langcode: fr
    uuid: 8596cb8f-b866-4cd3-9127-7cab0ef7df72
    bundle: picto_et_texte
    revision_id: null
    rev_id_current: null
    fields:
      field_picto_et_texte:
        -
          target_id: '52'
          target_revision_id: '99'
        -
          target_id: '53'
          target_revision_id: '100'
        -
          target_id: '54'
          target_revision_id: '101'
        -
          target_id: '55'
          target_revision_id: '102'
  -
    info: 'Image en haut de page'
    langcode: fr
    uuid: cc9d0053-0d6f-4f30-aa51-bacb9710c2a3
    bundle: image
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '16'
          alt: mesh
          title: ''
          width: '64'
          height: '64'
  -
    info: 'Communiquer / Mutualiser'
    langcode: fr
    uuid: 72e90d94-a3c7-4a16-95c9-98bfa0191b1f
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p><a href="/">Lien wiki</a></p><p><a href="/">Lien discourse</a></p><p><a href="/">Lien nextcloud</a></p>'
          summary: ''
          format: basic_html
  -
    info: "En savoir plus sur l'adhésion"
    langcode: fr
    uuid: 04cf00ae-6b51-4aeb-8b25-b764c80e94aa
    bundle: lien
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Adhérer pour accéder à l'intégralité du contenu</p>"
          summary: ''
          format: full_html
      field_lien:
        -
          uri: 'internal:/'
          title: "En savoir plus sur l'adhésion"
          options: {  }
  -
    info: 'Dernière newsletter'
    langcode: fr
    uuid: 67095522-a276-4bcb-ac5e-024b0f8e5199
    bundle: lien
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
      field_lien:
        -
          uri: 'internal:/'
          title: 'Voir la dernière newsletter'
          options: {  }
  -
    info: "Actions dans l'association"
    langcode: fr
    uuid: d1dbc935-9685-453f-b144-b6b413e092d3
    bundle: taxonomies
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
      field_taxonomie:
        -
          target_id: '5'
        -
          target_id: '6'
        -
          target_id: '7'
        -
          target_id: '8'
  -
    info: OpenStreetMap
    langcode: fr
    uuid: 51336add-2e63-44f0-b9f3-e0bfabd7b279
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p><iframe src="https://www.openstreetmap.org/export/embed.html?bbox=3.874493837356568%2C43.64427623081348%2C3.8778921961784367%2C43.646040528752174&amp;layer=mapnik" width="415" height="250"></iframe></p>'
          summary: ''
          format: full_html
  -
    info: 'Adresse et contact'
    langcode: fr
    uuid: 062b31d8-76b5-4710-91ac-088969c978c7
    bundle: adresse_et_contact
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>Maison de la télédétection<br>500, rue Jean-François Breton<br>34093 Montpellier Cedex 5</p>'
          summary: ''
          format: basic_html
      field_email:
        -
          value: contact@openig.org
      field_telephone:
        -
          value: '04 67 55 86 54'
  -
    info: 'Description accueil'
    langcode: fr
    uuid: 8c419593-e0f3-47c9-b2e9-4118e5b46a0f
    bundle: texte_et_couleur
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>'
          summary: ''
          format: basic_html
      field_couleur:
        -
          color: '#F0F0EF'
          opacity: null
      field_lien:
        -
          uri: 'internal:/'
          title: 'En savoir plus'
          options: {  }
menus:
  -
    menu_name: footer
    title: 'Mentions légales'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 5b0408e5-146f-4c06-b848-46915d1a93f5
    options: {  }
  -
    menu_name: footer
    title: 'Plan du site'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 7efb7964-3bbd-40c3-96f3-2b2f80869de3
    options: {  }
  -
    menu_name: footer
    title: RGPD
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: bcd022eb-9a4e-4955-bb71-8ab50ed19eaa
    options: {  }
  -
    menu_name: footer
    title: CGU
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: f9b22e23-9d6e-4b17-ac79-1ee475ad9504
    options: {  }
  -
    menu_name: footer
    title: Contact
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: cc1f90e4-b5ef-4cd0-9482-4e876ccbb523
    options: {  }
  -
    menu_name: adhesion
    title: 'Pourquoi adhérer'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: b20fa811-542b-4567-8296-e0cc9ffc0874
    options: {  }
  -
    menu_name: adhesion
    title: 'Mon compte'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: db9dd5ac-fdad-4d99-9771-f62f88e71967
    options: {  }
  -
    menu_name: adhesion
    title: 'Nom utilisateur'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: 1d617429-90b2-45d9-ad43-8e2ab04b0d94
    options: {  }
  -
    menu_name: naviguer
    title: OPenIG
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 703618c2-4108-46ee-b431-435d675e2a73
    options: {  }
  -
    menu_name: naviguer
    title: Annuaire
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 1d764f88-fd5d-4fa3-8454-46436b8502b3
    options: {  }
  -
    menu_name: naviguer
    title: Données
    parent: null
    uri: 'https://ckan.openig.org/dataset'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: f18e8d78-a874-48a1-b73d-c04a48e3cffc
    options: {  }
  -
    menu_name: naviguer
    title: 'Groupes de travail'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: eff03693-aece-4fbc-843f-2af1845903bb
    options: {  }
  -
    menu_name: naviguer
    title: Services
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: e1c293de-c8e4-46eb-a982-050049e4c640
    options: {  }
  -
    menu_name: naviguer
    title: Agenda
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: fr
    uuid: b9d018cb-7f5f-49b3-bc79-5697ba69834c
    options: {  }
  -
    menu_name: naviguer
    title: Actualités
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: fr
    uuid: df23a192-bec0-42d2-a28b-ec8ce64c75ba
    options: {  }
  -
    menu_name: main
    title: OPenIG
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: ac5b7b14-b943-464e-bc9f-77e35bd4eeb6
    options: {  }
  -
    menu_name: main
    title: "Présentation d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'entity:node/10'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 7b5b96bb-1be4-46e9-8642-5d5ecd4251ba
    options: {  }
  -
    menu_name: main
    title: 'Réseaux et partenaires'
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 2937f7ac-a4eb-4bbd-be30-3f0c4e9278e4
    options: {  }
  -
    menu_name: main
    title: "L'association"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: c7e5dd55-4a0b-4326-9ec9-46c9ea34e6ea
    options: {  }
  -
    menu_name: main
    title: "Les adhérents d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: c3dbe0c5-d2f2-4d3d-8967-48f060279769
    options: {  }
  -
    menu_name: main
    title: "L'équipe"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: 9fbd32ea-a578-4b17-abbc-3366c58a23dc
    options: {  }
  -
    menu_name: main
    title: Annuaire
    parent: null
    uri: 'entity:node/11'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: ca8bd41d-849b-4006-9ff3-762eeeb17b4b
    options: {  }
  -
    menu_name: main
    title: Données
    parent: null
    uri: 'https://ckan.openig.org/dataset'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: d9144fe6-69e0-4976-819f-6ec224236685
    options: {  }
  -
    menu_name: main
    title: 'Groupe de travail'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: c1734394-cd4d-42e1-9549-612c89292052
    options: {  }
  -
    menu_name: main
    title: Services
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: fr
    uuid: 59f25bfd-6ad9-4428-80dd-cb76f3c8c7ed
    options: {  }
  -
    menu_name: main
    title: Agenda
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: fr
    uuid: d0168de7-927d-4c5e-8516-19f3a8fd5e2e
    options: {  }
  -
    menu_name: main
    title: Actualités
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: fr
    uuid: 02a94da8-d7ba-4de2-a0bc-1a486ad102be
    options: {  }
  -
    menu_name: faq
    title: FAQ
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: fr
    uuid: 676720fd-9c04-441d-9ab1-f4efdf169952
    options: {  }
taxonomies:
  actions_dans_l_association:
    -
      vid: actions_dans_l_association
      tid: '1'
      langcode: fr
      name: Découvrir
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3b2833cf-8340-4321-b87f-224c9903d513
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '32'
          alt: découvrir
          title: ''
          width: '64'
          height: '64'
    -
      vid: actions_dans_l_association
      tid: '3'
      langcode: fr
      name: Participer
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3e91e4aa-4bc8-46af-9b1c-545105d2cbd3
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '29'
          alt: participer
          title: ''
          width: '64'
          height: '64'
    -
      vid: actions_dans_l_association
      tid: '2'
      langcode: fr
      name: "S'informer"
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 90972cf5-6ed0-425c-86cd-cf91bdf4c765
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '28'
          alt: "S'informer"
          title: ''
          width: '64'
          height: '64'
    -
      vid: actions_dans_l_association
      tid: '4'
      langcode: fr
      name: Utiliser
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3612dd00-9baf-4377-8c33-896448300500
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '30'
          alt: Utiliser
          title: ''
          width: '64'
          height: '64'
  dpt_intervention: {  }
  outil_competence: {  }
  tags: {  }
  type_de_ressource: {  }
  typologie_de_structure: {  }
