blocks:
  -
    info: "En savoir plus sur l'adhésion"
    langcode: fr
    uuid: 04cf00ae-6b51-4aeb-8b25-b764c80e94aa
    bundle: lien
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Adhérer pour accéder à l'intégralité du contenu</p>"
          summary: ''
          format: full_html
      field_lien:
        -
          uri: 'internal:/'
          title: "En savoir plus sur l'adhésion"
          options: {  }
menus:
  -
    menu_name: footer
    title: 'Mentions légales'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 5b0408e5-146f-4c06-b848-46915d1a93f5
    options: {  }
  -
    menu_name: footer
    title: 'Plan du site'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 7efb7964-3bbd-40c3-96f3-2b2f80869de3
    options: {  }
  -
    menu_name: footer
    title: RGPD
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: bcd022eb-9a4e-4955-bb71-8ab50ed19eaa
    options: {  }
  -
    menu_name: footer
    title: CGU
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: f9b22e23-9d6e-4b17-ac79-1ee475ad9504
    options: {  }
  -
    menu_name: footer
    title: Contact
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: cc1f90e4-b5ef-4cd0-9482-4e876ccbb523
    options: {  }
  -
    menu_name: adhesion
    title: 'Pourquoi adhérer'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: b20fa811-542b-4567-8296-e0cc9ffc0874
    options: {  }
  -
    menu_name: adhesion
    title: 'Mon compte'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: db9dd5ac-fdad-4d99-9771-f62f88e71967
    options: {  }
  -
    menu_name: adhesion
    title: 'Nom utilisateur'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: 1d617429-90b2-45d9-ad43-8e2ab04b0d94
    options: {  }
  -
    menu_name: naviguer
    title: OPenIG
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 703618c2-4108-46ee-b431-435d675e2a73
    options: {  }
  -
    menu_name: naviguer
    title: Annuaire
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 1d764f88-fd5d-4fa3-8454-46436b8502b3
    options: {  }
  -
    menu_name: naviguer
    title: Données
    parent: null
    uri: 'https://ckan.openig.org/dataset'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: f18e8d78-a874-48a1-b73d-c04a48e3cffc
    options: {  }
  -
    menu_name: naviguer
    title: 'Groupes de travail'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: eff03693-aece-4fbc-843f-2af1845903bb
    options: {  }
  -
    menu_name: naviguer
    title: Services
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: e1c293de-c8e4-46eb-a982-050049e4c640
    options: {  }
  -
    menu_name: naviguer
    title: Agenda
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: fr
    uuid: b9d018cb-7f5f-49b3-bc79-5697ba69834c
    options: {  }
  -
    menu_name: naviguer
    title: Actualités
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: fr
    uuid: df23a192-bec0-42d2-a28b-ec8ce64c75ba
    options: {  }
  -
    menu_name: main
    title: OPenIG
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: ac5b7b14-b943-464e-bc9f-77e35bd4eeb6
    options: {  }
  -
    menu_name: main
    title: "Présentation d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'entity:node/10'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: fr
    uuid: 7b5b96bb-1be4-46e9-8642-5d5ecd4251ba
    options: {  }
  -
    menu_name: main
    title: 'Réseaux et partenaires'
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: fr
    uuid: 2937f7ac-a4eb-4bbd-be30-3f0c4e9278e4
    options: {  }
  -
    menu_name: main
    title: "L'association"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: c7e5dd55-4a0b-4326-9ec9-46c9ea34e6ea
    options: {  }
  -
    menu_name: main
    title: "Les adhérents d'OPenIG"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: c3dbe0c5-d2f2-4d3d-8967-48f060279769
    options: {  }
  -
    menu_name: main
    title: "L'équipe"
    parent: 'menu_link_content:ac5b7b14-b943-464e-bc9f-77e35bd4eeb6'
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: 9fbd32ea-a578-4b17-abbc-3366c58a23dc
    options: {  }
  -
    menu_name: main
    title: Annuaire
    parent: null
    uri: 'entity:node/11'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: fr
    uuid: ca8bd41d-849b-4006-9ff3-762eeeb17b4b
    options: {  }
  -
    menu_name: main
    title: Données
    parent: null
    uri: 'https://ckan.openig.org/dataset'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -47
    langcode: fr
    uuid: d9144fe6-69e0-4976-819f-6ec224236685
    options: {  }
  -
    menu_name: main
    title: 'Groupe de travail'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: fr
    uuid: c1734394-cd4d-42e1-9549-612c89292052
    options: {  }
  -
    menu_name: main
    title: Services
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: fr
    uuid: 59f25bfd-6ad9-4428-80dd-cb76f3c8c7ed
    options: {  }
  -
    menu_name: main
    title: Agenda
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -44
    langcode: fr
    uuid: d0168de7-927d-4c5e-8516-19f3a8fd5e2e
    options: {  }
  -
    menu_name: main
    title: Actualités
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -43
    langcode: fr
    uuid: 02a94da8-d7ba-4de2-a0bc-1a486ad102be
    options: {  }
  -
    menu_name: faq
    title: FAQ
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: fr
    uuid: 676720fd-9c04-441d-9ab1-f4efdf169952
    options: {  }
taxonomies:
  actions_dans_l_association:
    -
      vid: actions_dans_l_association
      tid: '1'
      langcode: fr
      name: Découvrir
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3b2833cf-8340-4321-b87f-224c9903d513
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '32'
          alt: découvrir
          title: ''
          width: '64'
          height: '64'
    -
      vid: actions_dans_l_association
      tid: '3'
      langcode: fr
      name: Participer
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3e91e4aa-4bc8-46af-9b1c-545105d2cbd3
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '29'
          alt: participer
          title: ''
          width: '64'
          height: '64'
    -
      vid: actions_dans_l_association
      tid: '2'
      langcode: fr
      name: "S'informer"
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 90972cf5-6ed0-425c-86cd-cf91bdf4c765
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '28'
          alt: "S'informer"
          title: ''
          width: '64'
          height: '64'
    -
      vid: actions_dans_l_association
      tid: '4'
      langcode: fr
      name: Utiliser
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3612dd00-9baf-4377-8c33-896448300500
      field_lien:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
      field_picto:
        -
          target_id: '30'
          alt: Utiliser
          title: ''
          width: '64'
          height: '64'
  dpt_intervention: {  }
  outil_competence: {  }
  tags: {  }
  type_de_ressource: {  }
  typologie_de_structure: {  }
