_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: fr
uuid: 10bccc0b-b145-46b3-8055-becd65b1e674
name: 'Occitanie Pyrénées en Intelligence Géomatique'
mail: webmaster@openig.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
