_core:
  default_config_hash: hpWLdd5VAF-3d5GvAxpnWzqBP7lYuWYaU7emaPhnVko
langcode: fr
type: role
mail_to: ''
roles:
  administrator: administrator
  authenticated: '0'
  content_editor: '0'
  adherent: '0'
mail_from: ''
mail_reply_to: ''
created_subject: 'Nouvelle création de compte :  [user:name]'
created_body: "Nouvelle création de compte : [user:name]\r\n\r\nVoir la fiche utilisateur: [user:url]\r\nÉditer l'utilisateur : [user:edit-url]\r\nSupprimer l'utilisateur : [user:cancel-url]"
updated_subject: 'Existing User "[user:name]" was updated / edited at [site:name] ([site:url], [current-date:short]'
updated_body: "User \"[user:name]\" ([user:url]) was updated / edited\r\nat [site:name] ([site:url]), [current-date:short]\r\n\r\nView user: [user:url]\r\nEdit user: [user:edit-url]\r\nDelete user: [user:cancel-url]\r\n\r\n---\r\nThe user was edited by [current-user:name] ([current-user:url])"
deleted_subject: 'User [user:name] was deleted at [site:name] ([site:url], [current-date:short]'
deleted_body: "User \"[user:name]\" ([user:url]) was deleted at [site:name] ([site:url]), [current-date:short]\r\n\r\n---\r\nThe user was deleted by [current-user:name] ([current-user:url])"
events:
  create: create
  update: '0'
  delete: '0'
mail_message_ids_header_overwrite_header:
  user_register_notify_user_register_notify_create: '0'
  user_register_notify_user_register_notify_update: '0'
  user_register_notify_user_register_notify_delete: '0'
  user_register_admin_created: '0'
  user_register_no_approval_required: '0'
  user_register_pending_approval_admin: '0'
  user_register_pending_approval: '0'
  user_status_activated: '0'
  user_status_blocked: '0'
  user_cancel_confirm: '0'
  user_status_canceled: '0'
  user_password_reset: '0'
created_roles_mode: exclude
created_roles:
  authenticated: '0'
  content_editor: '0'
  administrator: '0'
  adherent: '0'
updated_roles_mode: exclude
updated_roles:
  authenticated: '0'
  content_editor: '0'
  administrator: '0'
  adherent: '0'
deleted_roles_mode: exclude
deleted_roles:
  authenticated: '0'
  content_editor: '0'
  administrator: '0'
  adherent: '0'
enable_logging: false
