<?php

/**
 * Implements hook_theme().
 */
function openig_search_theme() {
    return [
        'openig_search_results' => [
            'variables' => [
                'items' => [],
                'facets' => [],
                'filters' => [],
                'pager' => [],
                'page' => '',
                'count' => '',
                'url' => ''
            ],
        ],
    ];
}

function openig_search_preprocess_openig_search_results(&$variables) {
    $variables['#attached']['library'][] = 'openig_search/openig-search';
}

function openig_search_preprocess(&$variables, $hook) {
  // Add images path alias
  $variables['images_path'] = \Drupal::request()->getSchemeAndHttpHost() . '/' . \Drupal::service('extension.list.module')->getPath('openig_search') . '/images/';
}

