<?php

/**
 * @file
 * OPenIG theme file.
 */

 function openig_preprocess_form_element_label(&$variables){
   // $variables['title_display'] = '';
   // $variables['title']['#markup'] = 'Rechercher';
 }

 function openig_preprocess_input(&$variables){
    if(($variables['theme_hook_original'] == 'input__submit') and ($variables['element']['#type'] == 'submit')){
        $variables['attributes']['value'] = '';
    }
 }