name: OPenIG Config
type: module
description: OPenIG Configuration
package: Custom
core_version_requirement: ^10
dependencies:
  - paragraphs
  - admin_toolbar
  - webform
  - weight
  - sync_uuids
  - social_media_links
  - social_media_links_field
  - simplenews
