<?php

use Drupal\user\UserInterface;
use Drupal\simplenews\Entity\Subscriber;
use Symfony\Component\Ldap\Entry;

function openig_ldap_ldap_user_edit_user_alter(UserInterface $account, Entry $entry, array $context) {
  /** @var \Drupal\ldap_servers\Processor\TokenProcessor $tokenProcessor */
  $tokenProcessor = \Drupal::service('ldap.token_processor');

  // dump($account);
  // $value = $tokenProcessor->ldapEntryReplacementsForDrupalAccount($entry, '[sn]');
  // $account->set('field_phone', "02 XX XX XX XX");

  // TODO 1 - synchro des réseaux sociaux
  // dump( $account->get('field_social_network') );
  // dump( $platforms = \Drupal::service('plugin.manager.social_media_links.platform')->getPlatformsSortedByWeight([]) );
  
  // 2 - synchro de la structure d'appartenance
  // dump( $tokenProcessor->ldapEntryReplacementsForDrupalAccount($entry, '[structureUid]') );
  // dump( $account->get('field_structure') );
  $storage = \Drupal::entityTypeManager()->getStorage('node');
  $structures = $storage->loadByProperties(['type' => 'structure', 'field_ldap_uid' => $tokenProcessor->ldapEntryReplacementsForDrupalAccount($entry, '[structureUid]')]);
  if(!empty($structures)) {
    // associate user with structure
    $account->set('field_structure', array_values($structures)[0]->nid->value );
  } else {
    // else delete structure association
    $account->set('field_structure', null );
  }

  // 3 - rattachement à la newsletter (si création d'un nouveau user)
  if ($account->isNew()) {
    // Create subscriber
    // $subscriber = Subscriber::loadByUid($account->id());
    $subscriber = Subscriber::loadByMail($account->getEmail(), 'create');
    $subscriber->fillFromAccount($account)->save();
    
    // Associate subscriber to newsletter
    $subscriber->subscribe('default');
    $subscriber->save();
  }

  // die();
}

