<?php

use \Drupal\views\Plugin\views\query\QueryPluginBase;
use \Drupal\views\ViewExecutable;


function openig_search_internal_views_pre_render(ViewExecutable $view){
  if (isset($view) && ($view->storage->id() == 'resultats_de_recherche')) {
    $view->element['#attached']['library'][] = 'openig_search_internal/openig_search_internal';
  }
}


function openig_search_internal_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if (($view->id() == 'resultats_de_recherche') && $view->current_display == 'block_filter_search_internal') {
    $query = $view->getQuery();
    $query->options['skip_access'] = true;
	}
}


function openig_search_internal_preprocess_views_view_fields__block_filter_search_internal(&$variables){
  // Check si la ressource est inaccessible
  $node_check = $variables['row']->_object->getEntity();
  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  $check = $node_check->access('view', $user);
  $variables['accessCheck'] = $check;

  // Surcharge des liens "En savoir plus" suivant le type de contenu
  if($variables['row']->_object->getEntity()->type->target_id === "evenement"){
    $nid = $variables['row']->_object->getEntity()->nid->value;
    $variables['urlCustom'] = '/l-agenda?id='.$nid;
  }
  elseif($variables['row']->_object->getEntity()->type->target_id === "ressource"){
    // Si champ lien alors affichage
    if(!empty($variables['row']->_object->getEntity()->field_link->getValue())){
      $variables['urlCustom'] = $variables['row']->_object->getEntity()->field_link->getValue()[0]['uri'];
    }
    // Si champ fichier alors affichage
    elseif(!empty($variables['row']->_object->getEntity()->field_file->getValue())){
      // Récupération du fichier
      $file = \Drupal::entityTypeManager()->getStorage('file')->load($variables['row']->_object->getEntity()->field_file->getValue()[0]['target_id']);
      $variables['urlCustom'] = \Drupal::service('file_url_generator')->generate($file->uri->getValue()[0]['value']);
    }
    // Si champ image alors affichage
    elseif(!empty($variables['row']->_object->getEntity()->field_image->getValue())){
      // Récupération de l'image
      $file_img = \Drupal::entityTypeManager()->getStorage('file')->load($variables['row']->_object->getEntity()->field_image->getValue()[0]['target_id']);
      $variables['urlCustom'] = \Drupal::service('file_url_generator')->generate($file_img->uri->getValue()[0]['value']);
    }
    else{
      $variables['urlCustom'] = null;
    }
  }
  else{
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $nid = $variables['row']->_object->getEntity()->nid->value;
    $alias = \Drupal::service('path_alias.manager')->getAliasByPath('/node/'.$nid, ($langcode));
    $variables['urlCustom'] = $alias;
  }
}
